import type { Metadata } from "next";
import "./styles/globals.css";
import { SlotModalProvider } from "@/providers/SlotBookProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SlotModalProvider>
        <body>{children}</body>
      </SlotModalProvider>
    </html>
  );
}
