import type { Metadata } from "next";
import "./styles/globals.css";
import { SlotModalProvider } from "@/providers/SlotBookProvider";
import ReactQueryProvider from "@/providers/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <SlotModalProvider>
          <body>{children}</body>
        </SlotModalProvider>
      </ReactQueryProvider>
    </html>
  );
}
